### ISSUE TITLE
Navigation does not remain fixed

### ISSUE THREAD

**Issue by Alexie81** [googleforgames/open-saves#210]
**_Hello,_** 

**My name is Alexie.**
#
I have a suggestion:

Navigation doesn't stand still when I scroll down only when I scroll up again, and this is pretty annoying. 
I think you should stay put whether you scroll up or scroll down and just leave:

```
$(function () {

    $(window).scroll(function () {

        if ($(this).scrollTop() < 50) {
            // hide nav
            $("nav").removeClass("vesco-top-nav");
            $("#back-to-top").fadeOut();

        } else {
            // show nav
            $("nav").addClass("vesco-top-nav");
            $("#back-to-top").fadeIn();
        }
    });
});
```
#
**_I hope I was helpful, it's just a personal opinion..._**

**Comment by yuryu** [comment]
Open Saves does not have UI. I think you opened this on the wrong project?

**Comment by Alexie81** [comment]
> Open Saves does not have UI. I think you opened this on the wrong project?

**_yeah, sorry, for the site is this issue_**
