### ISSUE TITLE
numberOfChunks property removal from initUpload for chunk data

### ISSUE THREAD

**Issue by labheshd** [googleforgames/open-saves#316]
**Is your feature request related to a problem? Please describe.**
Recently, the numberOfChunks property was removed from the initUpload request on Open saves. I think from a data reliability point of view, this numberOfChunks property being passed up from the client during an upload, gives the server a concrete guideline on how many chunks to expect from the client. 
Ex: without the numberOfChunks property being passed up from the client, and the server calculating the numberOfChunks on the fly- The server will have no idea if the complete data was uploaded or not. Even if one chunk upload request didn't get completed, the server won't know if the data is complete or not, and the client will get corrupted  data during download.     

**Describe the solution you'd like**
The numberOfChunks property is allowed to be passed up from the client during an initUpload operation instead of calculating this property on the fly on the open saves side.

**Comment by yuryu** [comment]
Merging into #313.
