### ISSUE TITLE
Provide a QueryRecordKeys stream message

### ISSUE THREAD

**Issue by loranger2k** [googleforgames/open-saves#344]
**Is your feature request related to a problem? Please describe.**
We currently have two issues with the QueryRecord unary gRPC message:
1. Inconsistent performance when querying data for records with large opaque strings.
2. Reaching limits on unary gRPC message length (4 MB)

**Describe the solution you'd like**
I would like to get a streaming gRPC endpoint to query data and only return the Keys of the records that are found. It would be best if the new message includes support for pagination with support for offset and limit. Since we would deal with only keys, there won't be huge penalty to pay to "skip" the keys that are not desired prior to the offset in the request.

This will fix a couple of issues we have with the current implementation:
1. When the size of the data returned is large, the unary message in gRPC gets passed the default 4MB max size. Using a streaming gRPC message will address the issue.
3. For records with large opaque strings, we won't be able to get consistent performance. Only returning the Keys (which is supported in Datastore) will work around the variable record sizes.

**Describe alternatives you've considered**
There is currently no alternative as the query endpoint is a unary message and returns the complete entities in the responses. Also, there is no clean way to expose the "Cursor" functionality of Datastore to the client to browse through the entities.

**Additional context**

**Comment by hongalex** [comment]
After offline discussion, we can provide this without support for offset (due to performance issues). Also consider exposing QueryRecord and an option for `KeysOnly`.

**Comment by yuryu** [comment]
Another consideration is to make QueryRecords a streaming method. It'd break compatibilities but I believe it's the right change for long-term. Ideally we want to land it before 1.0.0.

**Comment by loranger2k** [comment]
Breaking compatibility gives us a chance to also support returning only keys and specifying an offset (supported only when keys are returned, not whole records).
