### ISSUE TITLE
Support a health check endpoint to use as readiness and liveness kubernetes probes

### ISSUE THREAD

**Issue by loranger2k** [googleforgames/open-saves#378]
**Is your feature request related to a problem? Please describe.**
Lack of readiness / liveness probes, which is needed for a graceful server shutdown.

**Describe the solution you'd like**
I'd like to get a gRPC server for health check, and use it to set up the readiness and liveness probes when running in kubernetes.

**Describe alternatives you've considered**
Not sure if there is a good alternative.

**Additional context**
N/A

**Comment by yuryu** [comment]
I thought `Ping` might work here but apparently not.

- https://cloud.google.com/blog/topics/developers-practitioners/health-checking-your-grpc-servers-gke
- https://github.com/grpc/grpc/blob/master/doc/health-checking.md

This makes `Ping` a bit redundant but not exactly, so I think having both would make sense.

**Comment by yuryu** [comment]
On second thought, I think it makes sense to deprecate/remove `Ping` as health check was the only legitimate use case.

**Comment by loranger2k** [comment]
Well, our gateway is using the Ping interface to determine if it can be considered as healthy itself.

The Kubernetes health check endpoints do not need to be available outside of the cluster.

**Comment by yuryu** [comment]
Can you elaborate why you'd need two kinds of health checks? Do you expect to see different results from the two methods in certain cases?

**Comment by loranger2k** [comment]
No, we do not need a different results. I was simply pointing that Ping is part of the public interface, while the Kubernetes health check probes is usually internal to the cluster.

**Comment by yuryu** [comment]
I think we can say "Open Saves implements the GRPC Health Checking Protocol" and it can be used publicly. The protocol is independent from the k8s health check probes.
