### ISSUE TITLE
Support for graceful server shutdown to address potential issues when pods are scaling down / terminating

### ISSUE THREAD

**Issue by loranger2k** [googleforgames/open-saves#379]
**Is your feature request related to a problem? Please describe.**
When a k8s cluster is scaling down its number of pods, the service must respond to the SIGTERM sent by the control plane to stop accepting connection and draining the current connections before existing.

**Describe the solution you'd like**
Provide a graceful server shutdown implementation that makes sure no ongoing requests are going to be dropped when pods are terminating (when the service scales down or when doing a rolling deployment). One example of implementing a graceful server shutdown using OS signals can be found here: https://gist.github.com/embano1/e0bf49d24f1cdd07cffad93097c04f0a 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yuryu** [comment]
I'm not sure if I understand "graceful shutdowns" correctly here. I thought the server would finish serving ongoing requests but the PR doesn't seem to work like that.

> the service must respond to the SIGTERM sent by the control plane to stop accepting connection and draining the current connections before existing.

What do you mean by "draining"?

**Comment by loranger2k** [comment]
draining == finish serving the on-flight requests.
