### ISSUE TITLE
github.com/golang/protobuf is deprecated

### ISSUE THREAD

**Issue by aimuz** [googleforgames/open-saves#412]
**What happened**:

github.com/golang/protobuf is deprecated

https://github.com/golang/protobuf

**What you expected to happen**:

Use the "google.golang.org/protobuf" module instead

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Open Saves version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:

**Comment by yuryu** [comment]
Open Saves doesn't use `github.com/golang/protobuf` directly. It's used by dependencies, but they're out of our control.

```
❯ go mod why github.com/golang/protobuf
# github.com/golang/protobuf
(main module does not need package github.com/golang/protobuf)
```

**Comment by aimuz** [comment]
tools.go

```
github.com/golang/protobuf/protoc-gen-go
```

**Comment by aimuz** [comment]
I'm sorry, I must have handed over the wrong warehouse

https://github.com/googleforgames/agones
