### ISSUE TITLE
Expose binary objects in GCS publicly from a URL that expires after a configurable TTL

### ISSUE THREAD

**Issue by loranger2k** [googleforgames/open-saves#414]
**Is your feature request related to a problem? Please describe.**
This request comes from making some of the data saved in Open Saves available to 3rd party application using HTTP and no authorization to pull the data.

**Describe the solution you'd like**
I want to expose some of the binary objects saved in GCS through a public URL that is hard to guess and persist only for an amount of time that has a default configured in Open Saves that can be overridden by the client.

**Describe alternatives you've considered**
An alternative could be to develop our own GCS client to make the binary objects public without going through Open Saves. But we would like to avoid exposing GCS in our client.

**Additional context**

**Comment by markmandel** [comment]
Seems like Signed URLs would be a good fit? https://cloud.google.com/storage/docs/access-control/signing-urls-with-helpers#download-object

**Comment by loranger2k** [comment]
Yes, this is exactly what I had in mind! Thanks for sharing the link, Mark.
