### ISSUE TITLE
Define storage backend interfaces

### ISSUE THREAD

**Issue by yuryu** [googleforgames/open-saves#9]
**Is your feature request related to a problem? Please describe.**
As in the architecture, we need three interfaces that represent each of the backend storage classes.

**Describe the solution you'd like**
Each interface should include operations like CRUD and basic query if necessary. We can then implement interfaces for backing service providers, such as Cloud Datastore and Redis.

How we define the interfaces is TBD. We could use Go interfaces to define common operations, for example. Each backing services will be statically linked.

**Describe alternatives you've considered**
- Directly implementing providers without defining interfaces: While we prioritize the support for GCP backends but defining clear interfaces would help in the long run without introducing much complexity.
- Using the standard [go plugin](https://golang.org/pkg/plugin/): It is not meant to support dynamic loading of third party plugins. Also this only works on Linux, FreeBSD, and MacOS. Not suitable for our use case.
- Hashicorp's [go-plugin](https://github.com/hashicorp/go-plugin): This is a proven open-source plugin-system for Go that uses a multi-process architecture and gRPC calls. This could work well for our use case, however, we want to minimize the complexity and time to ship for the initial release. We might switch to this tool in the future when we implement additional backend providers.

**Additional context**
n/a

**Comment by hongalex** [comment]
Closing as obsolete.
